"""empty message

Revision ID: 445ceeff2654
Revises: f228b1625b73
Create Date: 2021-07-23 00:18:23.030350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '445ceeff2654'
down_revision = 'f228b1625b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planets', mysql.VARCHAR(length=120), nullable=False))
    # ### end Alembic commands ###
