"""empty message

Revision ID: d3c7325a7ace
Revises: fb0a329dfb05
Create Date: 2021-07-17 16:04:45.830609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c7325a7ace'
down_revision = 'fb0a329dfb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'people', ['name'])
    op.create_unique_constraint(None, 'planet', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'people', type_='unique')
    # ### end Alembic commands ###
