"""empty message

Revision ID: f228b1625b73
Revises: acbd46c25a01
Create Date: 2021-07-23 00:16:48.378828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f228b1625b73'
down_revision = 'acbd46c25a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'people', 'planet', ['planet_id'], ['id'])
    op.drop_constraint('planet_ibfk_1', 'planet', type_='foreignkey')
    op.drop_column('planet', 'id_people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('id_people', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planet_ibfk_1', 'planet', 'people', ['id_people'], ['id'])
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'planet_id')
    # ### end Alembic commands ###
