"""empty message

Revision ID: fb0a329dfb05
Revises: 2ceac25a9aa8
Create Date: 2021-07-17 15:08:01.416060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0a329dfb05'
down_revision = '2ceac25a9aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='people')
    op.drop_index('name_2', table_name='people')
    op.drop_index('name', table_name='planet')
    op.drop_index('name_2', table_name='planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_2', 'planet', ['name'], unique=False)
    op.create_index('name', 'planet', ['name'], unique=False)
    op.create_index('name_2', 'people', ['name'], unique=False)
    op.create_index('name', 'people', ['name'], unique=False)
    # ### end Alembic commands ###
